version: '3'

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - NODE_ENV=production
            - TOPIC=agrupamento_de_edital
            - ENG_REST_URL=${CAMUNDA_URL}
            - ENG_REST_USERNAME=${CAMUNDA_USERNAME}
            - ENG_REST_PASSWORD=${CAMUNDA_PASSWORD}
            - MAX_TASK_DURATION=30000
            - CAMUNDA_DOMAINS_HOST=${CAMUNDA_DOMAINS_HOST}
            - CAMUNDA_DOMAINS_PORT=${CAMUNDA_DOMAINS_PORT}
            - CAMUNDA_DOMAINS_USER=${CAMUNDA_DOMAINS_USER}
            - CAMUNDA_DOMAINS_DB=${CAMUNDA_DOMAINS_DB}
            - CAMUNDA_DOMAINS_PASS=${CAMUNDA_DOMAINS_PASS}
            - EFG_DOMAINS_DB=${EFG_DOMAINS_DB}
            - COTEC_DOMAINS_DB=${COTEC_DOMAINS_DB}
        volumes:
            - ./src:/home/python/app

networks:
  default:
    external: true
    name: backend
